- name: Ensure HAProxy is deployed
  hosts: lb_servers
  force_handlers: True

  roles:
    # The "haproxy" role has a dependency on the "firewall" role.
    # The "firewall" role requires a "firewall_rules" variable be defined.
    - role: haproxy
      firewall_rules:
        # Allow 80/tcp connections
        - port: 80/tcp

      haproxy_appservers:
      - name: serverb.lab.example.com
        ip: 172.25.250.11
        backend_port: 80
      - name: serverc.lab.example.com
        ip: 172.25.250.12
        backend_port: 80


